// Procedural-generation pools for the /BG simulation.
// None of this needs to be readable from the on-camera distance —
// it just needs to look like real engineering work at a glance.

export const CHAT_TITLES = [
  "Refactor auth middleware",
  "Migrate users table",
  "Debug payment retry loop",
  "Audit GraphQL resolvers",
  "Embed pipeline tuning",
  "Backfill missing timestamps",
  "Investigate cache miss spike",
  "Stream parser rewrite",
  "RBAC schema redesign",
  "Drizzle query optimization",
  "Webhook idempotency layer",
  "OAuth callback flow",
  "Edge function cold starts",
  "Inngest fan-out worker",
  "Search relevance tuning",
  "Worker pool starvation",
  "S3 multipart upload retries",
  "Token bucket rate limit",
  "Replica lag investigation",
  "Cron drift on Sunday jobs",
  "Vector index reindex job",
  "PII redaction pipeline",
  "Stripe webhook signature",
  "Postgres deadlock trace",
  "Feature flag rollout plan",
];

export const USER_PROMPTS = [
  "refactor the auth middleware to use jwt instead of session cookies, and keep the cookie path-restricted to /api",
  "why is the build failing on main? the last green commit was 3 hours ago",
  "add a debounce to the search input — 300ms feels right",
  "migrate the users table to include a last_active_at column, backfill from the sessions table",
  "write a script that backfills missing email verification timestamps from audit logs",
  "investigate why the cache hit rate dropped 12% yesterday around 14:00 UTC",
  "add unit tests for the payment retry handler — cover the partial-failure branch",
  "the inngest worker is dropping events under load. find out where.",
  "convert the entire orders module to use drizzle instead of raw pg queries",
  "audit every place we read from process.env at request time — that's a cold start tax",
  "the search results page renders twice on every keystroke. fix that.",
  "rewrite the webhook dispatcher to dedupe by signature within a 60s window",
  "show me every place in the codebase where we still use the old useAuth hook",
  "the embeddings service is returning 503 on ~2% of requests. add retry with jitter.",
  "split the monolithic settings page into per-tab routes with shared layout",
  "add a feature flag gate around the new onboarding flow — default off, allowlist by org id",
  "the postgres CPU is sitting at 70% steady-state. find the worst queries.",
  "we're double-charging on the annual upgrade path. trace it.",
  "add a kill switch for the AI suggestions feature, callable via admin endpoint",
  "the cron that recomputes leaderboards is timing out on saturdays only. why?",
  "rewrite the file upload progress reporting to use server-sent events",
  "every test that touches the queue is flaky. is it the fake clock?",
  "convert the markdown renderer to streaming so first paint is faster",
  "the vector store is returning duplicates for some queries. dedupe by source id.",
  "we need a soft-delete pattern across all tenant-scoped tables — design it",
];

// Lines for the assistant's prose response (not code).
// Mix sentence lengths; not every response should sound the same.
export const ASSISTANT_PROSE = [
  "Looking at this now. The middleware lives in `src/lib/auth/middleware.ts` and it currently hangs the request on a Redis lookup — that's the latency you were seeing.",
  "I traced it through the call graph. The retry loop is fine; the problem is upstream, in the idempotency key generation.",
  "Three places this could be failing. Let me check each.",
  "The cache key includes the user's locale, but the locale resolver wasn't memoized — so two requests with the same canonical key were producing different cache keys. That's the miss spike.",
  "Got it. I'll split this into two PRs: the schema change first, then the consumer changes.",
  "Before I touch anything: the failing test is a real regression, not flaky. The fixture changed when we updated drizzle to 0.45.",
  "Found it. The webhook dispatcher trims trailing whitespace from signatures before comparing, but Stripe's signatures can legitimately end in a base64 padding character.",
  "The drop correlates exactly with the deploy at 13:54 UTC. I'll bisect the commits.",
  "Two options here. We can either patch the existing handler or rewrite the dispatcher to be event-driven. The second is more invasive but solves three bugs at once.",
  "Done with the trace. The deadlock is between the orders update and the inventory decrement — different transaction ordering on retry.",
  "I read through the resolver. It's calling the loader once per parent, which is the N+1 you suspected.",
  "Quick sanity check before I make changes: is the staging database also affected, or just prod?",
  "Pushed a draft. The risky part is the migration — it locks the table for ~40s on a 12M row dataset. We should run it in maintenance.",
  "Confirming: this only fires when the worker count is above 8. Below that, the contention doesn't manifest.",
  "I'll start with the read path. The write path can stay where it is for now.",
  "Looking at the audit logs, every failure has the same upstream cause: the consent webhook is being sent before the user row commits.",
  "The cron is fine — it's the queue consumer that's drifting. The acks are batched and the batch flush is on a 60s timer, not on count.",
  "I'm going to add structured logging here before we change behavior. We don't have enough signal to know if my fix actually fixes it.",
];

// Code snippets — language-tagged so we can render with a tiny bit of "syntax color".
// These don't need to be real code; they need to LOOK like real code.
export type CodeSnippet = { lang: string; lines: string[] };

export const CODE_SNIPPETS: CodeSnippet[] = [
  {
    lang: "typescript",
    lines: [
      "export async function authenticate(req: Request): Promise<Session | null> {",
      "  const token = req.headers.get('authorization')?.slice(7);",
      "  if (!token) return null;",
      "",
      "  try {",
      "    const payload = await jwt.verify(token, SIGNING_KEY, {",
      "      algorithms: ['HS256'],",
      "      issuer: 'wexiq.ai',",
      "    });",
      "    return { userId: payload.sub, scopes: payload.scopes ?? [] };",
      "  } catch (err) {",
      "    logger.warn({ err }, 'auth.verify_failed');",
      "    return null;",
      "  }",
      "}",
    ],
  },
  {
    lang: "typescript",
    lines: [
      "const dispatcher = inngest.createFunction(",
      "  { id: 'webhook.dispatch', concurrency: { limit: 32 } },",
      "  { event: 'webhook.received' },",
      "  async ({ event, step }) => {",
      "    const sig = await step.run('verify', () => verifySignature(event.data));",
      "    if (!sig.valid) return { ok: false, reason: 'bad-signature' };",
      "    await step.sendEvent('webhook.queued', {",
      "      name: 'webhook.fanout',",
      "      data: { tenantId: sig.tenantId, payload: event.data.body },",
      "    });",
      "    return { ok: true };",
      "  },",
      ");",
    ],
  },
  {
    lang: "typescript",
    lines: [
      "type RetryOpts = { attempts: number; baseMs: number; jitter?: number };",
      "",
      "export async function withRetry<T>(",
      "  fn: () => Promise<T>,",
      "  opts: RetryOpts = { attempts: 3, baseMs: 200, jitter: 0.3 },",
      "): Promise<T> {",
      "  let lastErr: unknown;",
      "  for (let i = 0; i < opts.attempts; i++) {",
      "    try { return await fn(); }",
      "    catch (err) {",
      "      lastErr = err;",
      "      const backoff = opts.baseMs * Math.pow(2, i);",
      "      const j = backoff * (opts.jitter ?? 0) * Math.random();",
      "      await sleep(backoff + j);",
      "    }",
      "  }",
      "  throw lastErr;",
      "}",
    ],
  },
  {
    lang: "sql",
    lines: [
      "ALTER TABLE users",
      "  ADD COLUMN last_active_at TIMESTAMPTZ;",
      "",
      "UPDATE users u",
      "SET last_active_at = s.max_seen",
      "FROM (",
      "  SELECT user_id, MAX(seen_at) AS max_seen",
      "  FROM sessions",
      "  WHERE seen_at > NOW() - INTERVAL '90 days'",
      "  GROUP BY user_id",
      ") s",
      "WHERE u.id = s.user_id;",
      "",
      "CREATE INDEX CONCURRENTLY idx_users_last_active",
      "  ON users (last_active_at DESC NULLS LAST);",
    ],
  },
  {
    lang: "python",
    lines: [
      "def chunk_documents(docs: list[Document], target_tokens: int = 512):",
      "    \"\"\"Split documents into overlapping chunks for embedding.\"\"\"",
      "    chunks = []",
      "    for doc in docs:",
      "        tokens = tokenizer.encode(doc.text)",
      "        for i in range(0, len(tokens), target_tokens - 64):",
      "            window = tokens[i : i + target_tokens]",
      "            chunks.append(Chunk(",
      "                doc_id=doc.id,",
      "                offset=i,",
      "                text=tokenizer.decode(window),",
      "            ))",
      "    return chunks",
    ],
  },
  {
    lang: "typescript",
    lines: [
      "export const ratelimit = new TokenBucket({",
      "  capacity: 60,",
      "  refillPerSecond: 10,",
      "  keyFn: (req) => req.headers.get('x-tenant-id') ?? req.ip,",
      "});",
      "",
      "export async function gate(req: Request) {",
      "  const allowed = await ratelimit.consume(req, 1);",
      "  if (!allowed) {",
      "    return new Response('rate limited', { status: 429 });",
      "  }",
      "  return null;",
      "}",
    ],
  },
  {
    lang: "typescript",
    lines: [
      "useEffect(() => {",
      "  const ctrl = new AbortController();",
      "  fetch(`/api/search?q=${encodeURIComponent(query)}`, { signal: ctrl.signal })",
      "    .then((r) => r.json())",
      "    .then(setResults)",
      "    .catch((err) => {",
      "      if (err.name !== 'AbortError') console.error(err);",
      "    });",
      "  return () => ctrl.abort();",
      "}, [query]);",
    ],
  },
  {
    lang: "bash",
    lines: [
      "pnpm exec drizzle-kit generate --schema ./src/lib/db/schema.ts",
      "pnpm exec drizzle-kit push --strict",
      "pnpm exec tsx scripts/backfill-last-active.ts --batch 5000 --concurrency 4",
    ],
  },
  {
    lang: "json",
    lines: [
      "{",
      "  \"name\": \"webhook.dispatch\",",
      "  \"concurrency\": { \"limit\": 32, \"key\": \"event.data.tenantId\" },",
      "  \"throttle\": { \"period\": \"1m\", \"limit\": 600 },",
      "  \"retries\": { \"attempts\": 5, \"backoff\": \"exponential\" },",
      "  \"timeoutSeconds\": 30",
      "}",
    ],
  },
  {
    lang: "typescript",
    lines: [
      "export const users = pgTable('users', {",
      "  id: uuid('id').primaryKey().defaultRandom(),",
      "  email: text('email').notNull().unique(),",
      "  passwordHash: text('password_hash'),",
      "  createdAt: timestamp('created_at').defaultNow().notNull(),",
      "  lastActiveAt: timestamp('last_active_at'),",
      "  deletedAt: timestamp('deleted_at'),",
      "});",
      "",
      "export const sessions = pgTable('sessions', {",
      "  id: uuid('id').primaryKey().defaultRandom(),",
      "  userId: uuid('user_id').references(() => users.id).notNull(),",
      "  seenAt: timestamp('seen_at').defaultNow().notNull(),",
      "});",
    ],
  },
  {
    lang: "typescript",
    lines: [
      "type State =",
      "  | { status: 'idle' }",
      "  | { status: 'loading' }",
      "  | { status: 'ready'; data: Result }",
      "  | { status: 'error'; error: Error };",
      "",
      "function reducer(state: State, action: Action): State {",
      "  switch (action.type) {",
      "    case 'fetch':   return { status: 'loading' };",
      "    case 'success': return { status: 'ready', data: action.data };",
      "    case 'failure': return { status: 'error', error: action.error };",
      "    case 'reset':   return { status: 'idle' };",
      "  }",
      "}",
    ],
  },
];

// Diff snippets shown in tool blocks for "Edit" operations.
export type DiffLine = { kind: "add" | "del" | "ctx"; text: string };
export type DiffSnippet = { path: string; hunks: DiffLine[] };

export const DIFF_SNIPPETS: DiffSnippet[] = [
  {
    path: "src/lib/auth/middleware.ts",
    hunks: [
      { kind: "ctx", text: "export async function authenticate(req: Request) {" },
      { kind: "del", text: "  const session = await redis.get(`sess:${cookie}`);" },
      { kind: "del", text: "  if (!session) return null;" },
      { kind: "add", text: "  const token = req.headers.get('authorization')?.slice(7);" },
      { kind: "add", text: "  if (!token) return null;" },
      { kind: "add", text: "  const payload = await jwt.verify(token, SIGNING_KEY);" },
      { kind: "ctx", text: "  return { userId: payload.sub };" },
      { kind: "ctx", text: "}" },
    ],
  },
  {
    path: "src/app/api/webhooks/route.ts",
    hunks: [
      { kind: "ctx", text: "export async function POST(req: Request) {" },
      { kind: "ctx", text: "  const sig = req.headers.get('stripe-signature');" },
      { kind: "del", text: "  if (sig !== expected) return new Response('bad', { status: 400 });" },
      { kind: "add", text: "  if (!stripe.webhooks.verifyHeader(body, sig, secret)) {" },
      { kind: "add", text: "    return new Response('bad signature', { status: 400 });" },
      { kind: "add", text: "  }" },
      { kind: "ctx", text: "  const event = JSON.parse(body);" },
    ],
  },
  {
    path: "src/components/SearchBox.tsx",
    hunks: [
      { kind: "ctx", text: "const [query, setQuery] = useState('');" },
      { kind: "add", text: "const debounced = useDebounced(query, 300);" },
      { kind: "ctx", text: "" },
      { kind: "ctx", text: "useEffect(() => {" },
      { kind: "del", text: "  void search(query).then(setResults);" },
      { kind: "add", text: "  if (!debounced) { setResults([]); return; }" },
      { kind: "add", text: "  void search(debounced).then(setResults);" },
      { kind: "del", text: "}, [query]);" },
      { kind: "add", text: "}, [debounced]);" },
    ],
  },
  {
    path: "src/lib/db/schema.ts",
    hunks: [
      { kind: "ctx", text: "export const users = pgTable('users', {" },
      { kind: "ctx", text: "  id: uuid('id').primaryKey().defaultRandom()," },
      { kind: "ctx", text: "  email: text('email').notNull().unique()," },
      { kind: "add", text: "  lastActiveAt: timestamp('last_active_at')," },
      { kind: "add", text: "  deletedAt: timestamp('deleted_at')," },
      { kind: "ctx", text: "  createdAt: timestamp('created_at').defaultNow().notNull()," },
      { kind: "ctx", text: "});" },
    ],
  },
  {
    path: "src/lib/inngest/worker.ts",
    hunks: [
      { kind: "del", text: "  concurrency: { limit: 8 }," },
      { kind: "add", text: "  concurrency: { limit: 32, key: 'event.data.tenantId' }," },
      { kind: "ctx", text: "  retries: 5," },
      { kind: "add", text: "  throttle: { period: '1m', limit: 600 }," },
    ],
  },
];

// Claude Code-style tool invocations. The right pane uses these heavily.
export const TOOL_CALLS = [
  { name: "Read", args: "src/lib/auth/middleware.ts" },
  { name: "Read", args: "src/app/api/webhooks/route.ts" },
  { name: "Read", args: "src/lib/db/schema.ts" },
  { name: "Read", args: "src/components/SearchBox.tsx" },
  { name: "Read", args: "package.json" },
  { name: "Read", args: "next.config.ts" },
  { name: "Grep", args: "pattern: 'useAuth' --include '*.tsx'" },
  { name: "Grep", args: "pattern: 'process\\.env\\.' --include '*.ts'" },
  { name: "Grep", args: "pattern: 'TODO|FIXME' --include '*.ts'" },
  { name: "Glob", args: "src/**/*.test.ts" },
  { name: "Glob", args: "src/app/**/route.ts" },
  { name: "Bash", args: "pnpm exec tsc --noEmit" },
  { name: "Bash", args: "pnpm test src/lib/auth --run" },
  { name: "Bash", args: "git status" },
  { name: "Bash", args: "git diff src/lib/db/schema.ts" },
  { name: "Bash", args: "pnpm exec drizzle-kit generate" },
  { name: "Bash", args: "psql $DATABASE_URL -c '\\dt'" },
  { name: "Edit", args: "src/lib/auth/middleware.ts" },
  { name: "Edit", args: "src/app/api/webhooks/route.ts" },
  { name: "Edit", args: "src/components/SearchBox.tsx" },
  { name: "Edit", args: "src/lib/inngest/worker.ts" },
  { name: "Write", args: "scripts/backfill-last-active.ts" },
  { name: "Write", args: "src/lib/auth/jwt.ts" },
];

// Terminal-style output lines for the right pane. Random-looking but plausible.
export const TERMINAL_OUTPUT = [
  "✓ src/lib/auth/middleware.ts:42 — type-check passed",
  "✓ src/app/api/webhooks/route.ts:18 — type-check passed",
  "✗ src/lib/db/queries.ts:117 — Type 'string | null' is not assignable to 'string'",
  "  found 1 error in 1 file",
  "warning: unused import 'pgTable' in src/lib/db/schema.ts:3",
  "info: rebuilding 47 modules…",
  "✓ compiled in 2.1s",
  "PASS  src/lib/auth/middleware.test.ts (3.2s)",
  "PASS  src/lib/webhooks/dispatcher.test.ts (1.8s)",
  "FAIL  src/lib/queue/consumer.test.ts (4.1s)",
  "  ● drains queue under load › flushes within 60s",
  "    expected: < 60000",
  "    received: 71204",
  "Tests:       2 passed, 1 failed, 3 total",
  "Time:        9.124s",
  "[14:02:11] INFO  webhook.received tenant=t_8f3a evt=evt_K2x9",
  "[14:02:11] INFO  webhook.verified tenant=t_8f3a sig=ok",
  "[14:02:12] WARN  retry.backoff attempt=2 wait=412ms",
  "[14:02:13] ERROR upstream.timeout host=embeddings-svc",
  "[14:02:13] INFO  retry.scheduled attempt=3 wait=824ms",
  "Compiling…",
  "✓ Compiled /BG in 312ms",
  "✓ Compiled /api/auth/callback in 184ms",
  "GET  /api/health 200 in 4ms",
  "POST /api/webhooks 202 in 38ms",
  "POST /api/webhooks 202 in 41ms",
  "POST /api/auth/jwt  200 in 22ms",
  "GET  /dashboard     200 in 87ms",
  "drizzle-kit: applying migration 0042_add_last_active.sql",
  "drizzle-kit: ✓ migration applied (1.847s)",
  "lockfile is up to date, resolution step is skipped",
  "Progress: resolved 1247, reused 1247, downloaded 0, added 0, done",
];

// Some single-line "thinking" / status messages for the assistant.
export const STATUS_LINES = [
  "Reading the codebase to find every callsite…",
  "Checking the migration history first.",
  "Pulling the schema definition.",
  "Looking at the test for this behavior.",
  "Grepping for the old pattern.",
  "Tracing the call graph from the route handler.",
  "Verifying the type signatures line up.",
  "Running the test suite to confirm.",
  "Comparing against the previous deploy.",
];

export function pick<T>(arr: readonly T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

export function shortId(): string {
  return Math.random().toString(36).slice(2, 8);
}
